### PR TITLE
Fix typo in Content-Type

### PR DESCRIPTION
**Pull request by EmaX093**
Hi!! This PR fix the typo in content-type request

Now it does

``` http
Content-Type: application/jsoncharset=UTF-8
```

And it should do

``` http
Content-Type: application/json; charset=UTF-8
```

### CODE REVIEW

**Comment by christianalfoni** [comment]
What reference you have on this? I am very sure the semi colon is supposed to be there? :-)

**Comment by EmaX093** [comment]
Oh sorry, my english is not very shiny. I was trying to say the opposite. The Content-Type SHOULD have the semi colon that is missing right now on master, that is what this PR fix.

**Comment by saitodisse** [comment]
This error is why advanced tutorial is not working properly. When I force `Content-Type` the server accepts the data. Please merge

**Comment by christianalfoni** [comment]
Oh my, so sorry! Something wrong must have happened in merge. I did look over this, anyways publishing fix now :)

**Pull request merged**
