### PR TITLE
Support multiple file uploads

### PR DESCRIPTION
**Pull request by schotime**
Add xhr callback to enable control of request

### CODE REVIEW

**Comment by christianalfoni** [comment]
Looks good! Though some suggestions:

I think we actually should make `FileUpload` return an object:

``` js
const upload = new FileUpload(files, {})
upload.send()
   .then(this.props.uploadFinished)
   .catch(this.props.uploadFailed)

setTimeout(() => upload.abort())
```

Breaking change, but I think it is worth it. A lot cleaner I think. What do you think=?

**Comment by schotime** [comment]
Yeh. We thought about doing that but didn't want to do too much without a concensus.

We can have a look again tomorrow and I can update the PR and we can discuss further.

Cheers :)

**Comment by christianalfoni** [comment]
Awesome, thanks for bringing in ideas here! :)

**Comment by schotime** [comment]
I have updated. Have a look. ;)

**Comment by schotime** [comment]
Added an extension off http services as well which appends the baseUrl. Can use both ways. As a standalone or through http.

**Comment by christianalfoni** [comment]
Looking great! 💃  :)

**Pull request merged**
