### PR TITLE
Support for GET params

### PR DESCRIPTION
**Pull request by EmaX093**
This was working in previous cerebral-http-modules version. If I recall correctly this module was using Axios underhood, but now seems to use pure XMLHttpRequest. So I add this missing functionality to make this module work with my project again.

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi @Reltik!

Thanks for the update :-) Does it make sense to you to change the option to `query`? That way it complies with for example Express and is technically more correct. Do not know why Axios calls them params, as params are typically referred to dynamic url patterns, like: `/users/:id`, where `id`is the param.

I can bring it in and just change it, but just want to bring it up with you first :)

**Comment by EmaX093** [comment]
@christianalfoni Sounds good to me! I will update the code in a short while

**Comment by christianalfoni** [comment]
Great stuff, just taking a shower. Can pull in when you are ready, update website with new option and publish :)

**Comment by EmaX093** [comment]
Sorry for the mess!! I was trying to rebase my fork and the GitHub Desktop app was stuck in 'Updating' forever!!! So I did what you mention and rebase the code up to the lastests commits. I make some slightly change based on your last commit to reuse the urlEncode function in 'utils.js', 

I tried it in my project without any problem so far.

**Comment by christianalfoni** [comment]
@Reltik Hehe, I know the feeling, just ask @Guria ;-)

But is the only change here just urlEncoding the query option and attaching it to the url? If so I can just make a fix locally and close this PR. Will keep it a bit cleaner :)

**Comment by EmaX093** [comment]
Yes exactly, just need to update the utils.js file and index.js.

utils.js

``` js
module.exports.urlEncode = function urlEncode(obj) {
  var str = [];
  for (var p in obj) {  
    if (obj.hasOwnProperty(p)) {
        if(obj[p] instanceof Array)
        {
            var arrToUri = "";

            for(var i in obj[p]) {                      
                arrToUri += p + "[]" + "=" + obj[p][i] + "&";
            }

            str.push(arrToUri.substring(0, arrToUri.length - 1));
        }
        else 
            str.push(encodeURIComponent(p) + '=' + encodeURIComponent(obj[p]));
    }
  }
  return str.join('&');
}
```

index.js (LoC 139)

``` js
get: function (url, options) {
        options = options || {}

        if (options.query)      
            url += "?" + utils.urlEncode(options.query);

        options.url = url
        options.method = 'GET'
        return requestService(options)
      },
```

**Comment by christianalfoni** [comment]
And you extended the urlEncoder to handle arrays and stuff, which it should, okay... I will just fix this locally :)

**Comment by EmaX093** [comment]
Thank you @christianalfoni !

**Comment by christianalfoni** [comment]
Sweet working on it now, thanks for the pull though :)

**Pull request closed without merging**
